<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="xml" encoding="UTF-8" omit-xml-declaration="no" standalone="no" indent="yes"/> 
	<xsl:template match="/">
		<xsl:comment>
This file was generated automatically from a ribbon xml.
Do not edit this file, edit the original ribbon xml instead.
</xsl:comment>
      		<FreeplaneUIEntries>
      		<Entry builder="main_menu">
				<xsl:apply-templates select="/*/*/*"/>
			</Entry>
		</FreeplaneUIEntries>
	</xsl:template>
	
<xsl:template match="*">
	<xsl:element name="Entry" >
		<xsl:apply-templates select="@*"/>
			<xsl:if test="name() != 'ribbon_action'">
				<xsl:attribute name="builder">
					<xsl:choose>
						<xsl:when test="@name='home'">
							<xsl:text>ribbon_task,toolbar</xsl:text>
						</xsl:when>
						<xsl:when test="@name='ribbon_separator'">
							<xsl:text>separator</xsl:text>
						</xsl:when>
						<xsl:when test="@name='ribbon_task'">
							<xsl:text>ribbon_task,menu</xsl:text>
						</xsl:when>
						<xsl:when test="@name='menu_category'">
							<xsl:text>mainmenu</xsl:text>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="name()"/>
						</xsl:otherwise>
					</xsl:choose>
					
				</xsl:attribute>
			</xsl:if>
		<xsl:apply-templates select="*"/>
	</xsl:element>
</xsl:template>

<xsl:template match="@action">
	<xsl:attribute name="name">
			<xsl:value-of select="."/>
		</xsl:attribute>
</xsl:template>

<xsl:template match="@name_ref|@menu_key">
</xsl:template>

<xsl:template match="@*">
	<xsl:copy/>
</xsl:template>

</xsl:stylesheet>