/**
 * author: Marcel Genzmehr
 * 22.08.2011
 */
package org.docear.plugin.core.event;

/**
 * 
 */
public enum DocearEventType {
	NULL, NEW_INCOMING, LIBRARY_NEW_MINDMAP_INDEXING_REQUEST, LIBRARY_EMPTY_MINDMAP_INDEX_REQUEST, NEW_LIBRARY, PROPERTY_CHANGED, LIBRARY_NEW_REFERENCES_INDEXING_REQUEST, MINDMAP_ADD_PDF_TO_NODE, NEW_MY_PUBLICATIONS, NEW_LITERATURE_ANNOTATIONS

}
