/**
 * author: Marcel Genzmehr
 * 22.08.2011
 */
package org.docear.plugin.core.event;

/**
 * 
 */
public enum DocearEventType {
	NULL
	, NEW_LIBRARY
	, LIBRARY_NEW_MINDMAP_INDEXING_REQUEST
	, LIBRARY_NEW_PROJECT_INDEXING_REQUEST
	, LIBRARY_NEW_REFERENCES_INDEXING_REQUEST
	, NEW_MY_PUBLICATIONS
	, NEW_INCOMING
	, NEW_LITERATURE_ANNOTATIONS
	, LIBRARY_EMPTY_MINDMAP_INDEX_REQUEST
	, MINDMAP_ADD_PDF_TO_NODE
	, PROPERTY_CHANGED
	, LIBRARY_CHANGED

}
