/**
 * author: Marcel Genzmehr
 * 22.08.2011
 */
package org.docear.plugin.core.event;

/**
 * 
 */
public enum DocearEventType {
	NULL, NEW_LITERATURE_MAP, LIBRARY_NEW_MINDMAP_INDEXING_REQUEST, LIBRARY_EMPTY_MINDMAP_INDEX_REQUEST, NEW_LIBRARY, PROPERTY_CHANGED, LIBRARY_NEW_REFERENCES_INDEXING_REQUEST, PLUGIN_START_ALLOWED

}
